name: Godlike
main: me.marcoboekholt.mabonew.main
version: 1.0
author: Marco Boekholt
description: This plugin will give you the highest possible enchantment on armour and weapons.

commands:
  Sword:
    description: Get a sword with all enchantments
    permissions: Godlike.sword
  Armour:
    description: Get armour with all enchantments
    permissions: Godlike.armour
  Bow:
    description: Get bow with all enchantments
    permissions: Godlike.bow
  Tools:
    description: Get tools with all enchantments
    permissions: Godlike.tools
  God:
    description: Get the effect you get from eating an apple
    permissions: Godlike.god
  power:
    description: Get defence and strength powers
    permissions: Godlike.power
  fly:
    description: Get fly powers!
    permissions: Godlike.fly
  speed:
    description: Walk faster than normal
    permissions: Godlike.speed
    
permissions:
   Godlike.*:
     description: Gives you access to all Godlike commands
     children:
       Godlike.sword: true
       Godlike.armour: true
       Godlike.bow: true
       Godlike.tools: true
       Godlike.god: true
       Godlike.power: true
       Godlike.fly: true
       Godlike.speed: true
   Godlike.sword:
     description: Allows you to use the sword command
     default: op
   Godlike.armour:
     description: Allows you to use the armour command
     default: op
   Godlike.bow:
     description: Allows you to use the bow command
     default: op
   Godlike.tools:
     description: Allows you to use the tools command
     default: op
   Godlike.god:
     description: Allows you to get the golden apple effects
     default: op
   Godlike.power:
     description: Allows you to get Defence and Strength powers
     default: op
   Godlike.fly:
     description: Allows you to go fly
     default: op
   Godlike.speed:
     description: Allows you to walk faster than normal
     default: op